### ISSUE TITLE
No databindings

### ISSUE THREAD

**Issue by nutechmobile** [ntnhon/RecyclerViewRowOptionsDemo#1]
Where is the databinding folder??????

**Comment by ntnhon** [comment]
Hi, what is the exact error that you encounter? Databinding is already enabled in [app build.gradle](https://github.com/ntnhon/RecyclerViewRowOptionsDemo/blob/9bb1a5d55cbcb4e75beb190d353040ada7defde2/app/build.gradle#L19)

**Comment by nutechmobile** [comment]
Sorry, im new to Android. I didnt know that was a different way of referencing a layout object. lol
